title: Momism of the Day (MOD)
email: mom@summerhays.net
description: >- # this means to ignore newlines until "baseurl:"
        All {{ site.data.mom-csv.size }} momisms, all in one place
keywords: momisms, mom, expressions
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://mom.summerhays.net" # the base hostname & protocol for your site, e.g. http://example.com
#  For testing
# url: localhost:4000
icon: /assets/images/confused-smiley.avif

# Build settings
markdown: kramdown
plugins:
  - jemoji
    #  - jekyll-datapage-generator
#  - jekyll-coffeescript
#  - jekyll-feed

tipue_search:
  include:
    pages: true
  exclude:
    files: [search.html]

include: ['_pages',".htaccess"]

defaults:
  -
    scope:
      path: "_pages" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "default"
      permalink: ":basename"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/


page_gen-dirs: true # uncomment, if you prefer to generate named folders

page_gen:
  - data: 'mom-csv'
    template: 'dictionary'
    dir: 'fresh-dictionary'
      #    name: 'order'
    name_expr: record['order']
    title: 'momism'
      # og-description: 'definition'
      #    extension: 'md'
      #    
      #  - data: 'pets'
      #    template: 'pet'
      #    name: 'pet_name'
      #    dir: 'pets'
      #
      #  - index_files: false
      #    data: 'books'
      #    template: 'book'
      #    name: 'title'
      #    dir: 'all-books'
      #    debug: true
      #
      #  - data: 'books'
      #    template: 'book'
      #    name: 'title'
      #    dir: 'books-i-have-read'
      #    filter: read  # read is a boolean value in the YML file
      #
      #  # read is a boolean value in the YML file, but I need to test for
      #  # falsity (read: false). The field `filter` is no good and I need to
      #  # use filter_conditions
      #  - data: 'books'
      #    template: 'book'
      #    name: 'title'
      #    dir: 'books-i-have-not-read'
      #    filter_condition: "record['read'] == false"
      #
      #  - data: 'books'
      #    template: 'book'
      #    name: 'title'
      #    dir: 'books-by-orwell'
      #    filter_condition: "record['author'] == 'George Orwell'"
      #
      #  - data: 'hierarchy.people'
      #    template: 'profile'
      #    name: 'full_name'
      #    dir: 'hierarchy'
