
var tipuesearch = {"pages": [
  {"title": "[Insert the blank] life", "text": "Good morning. <em>Post-adolescent life!</em>", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/[Insert the blank] life"},
  {"title": "[Insert the blank] lives", "text": "Someone is following their usual pattern. <em>*burp!* Fermenter-mom lives! </em>", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/[Insert the blank] lives"},
  {"title": "A \"to-do\"", "text": "A party. <em>Mom: They are really having a to-do up there. Me: That is so going on the list.</em>", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/A \"to-do\""},
  {"title": "A bad \"cattitude.\"", "text": "Improper orneriness with respect to the cat.", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/A bad \"cattitude.\""},
  {"title": "A bug in his/her ear about something", "text": "Awaiting definition", "tags": "jQuery HTML5 CSS", "url": "https://docs.google.com/forms/d/e/1FAIpQLSdfmzsR2Z4hB9AG-CfEiPwZClB78tSY3SPVOWi4XbDCeGZQog/viewform"},
  {"title": "A bunch of hooie", "text": "Nonsense or bullshit", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/A bunch of hooie"},
  {"title": "A far cry from [insert the blank] ", "text": "A long distance away", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/A far cry from [insert the blank] "},
  {"title": "A hair past a freckle", "text": "I don't have a watch on", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/A hair past a freckle"},
  {"title": "A month of Sundays", "text": "Awaiting definition", "tags": "jQuery HTML5 CSS", "url": "https://docs.google.com/forms/d/e/1FAIpQLSdfmzsR2Z4hB9AG-CfEiPwZClB78tSY3SPVOWi4XbDCeGZQog/viewform"},
  {"title": "A regular gulley-washer", "text": "A powerful rainstorm", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/A regular gulley-washer"},
  {"title": "Abscond with", "text": "To take", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Abscond with"},
  {"title": "Academic medicine", "text": "Medical research", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Academic medicine"},
  {"title": "According to conventional wisdom...", "text": "Awaiting definition", "tags": "jQuery HTML5 CSS", "url": "https://docs.google.com/forms/d/e/1FAIpQLSdfmzsR2Z4hB9AG-CfEiPwZClB78tSY3SPVOWi4XbDCeGZQog/viewform"},
  {"title": "After my own heart ", "text": "A preferred style. <em>Phoebe was a feline after my own heart. </em>", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/After my own heart "},
  {"title": "After someone about something", "text": "To nag", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/After someone about something"},
  {"title": "Airdishconer", "text": "Air conditioner <strong>Mommentary: Among mom’s favorite kidisms</strong>", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Airdishconer"},
  {"title": "Albatross around one's neck", "text": "A heavy burden, an irritating obligation", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Albatross around one's neck"},
  {"title": "All right, let's mush", "text": "Let's go <strong>Mommentary: I think my dad made that one up, since I never heard anyone else say it.</strong>", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/All right, let's mush"},
  {"title": "Amscrez-vous", "text": "Pig French for scram", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Amscrez-vous"},
  {"title": "As sure as God made little green apples", "text": "Certainly", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/As sure as God made little green apples"},
  {"title": "Asking for it", "text": "To fail to prevent or be partially responsible for something unpleasant happening", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Asking for it"},
  {"title": "At the drop of a hat", "text": "Without delay or good reason", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/At the drop of a hat"},
  {"title": "Ay gavalt", "text": "Mom's Yiddish streak: expresses annoyance", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Ay gavalt"},
  {"title": "Baby doll", "text": "Refers to her daughter", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Baby doll"},
  {"title": "Back in a mo", "text": "I'll be back in a moment", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Back in a mo"},
  {"title": "Bass-ackwards", "text": "Inverse of ass-backwards", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Bass-ackwards"},
  {"title": "Bearding any goats", "text": "Awaiting definition", "tags": "jQuery HTML5 CSS", "url": "https://docs.google.com/forms/d/e/1FAIpQLSdfmzsR2Z4hB9AG-CfEiPwZClB78tSY3SPVOWi4XbDCeGZQog/viewform"},
  {"title": "Bedtime for Bonzos", "text": "Bedtime for you. <strong>Mommentary: This was the title of a Ronald Reagan movie. I don't think I'd want to include it in a list of momisms, no matter how much or little I might have ever said those words</strong>", "tags": "jQuery HTML5 CSS", "url": "https://en.wikipedia.org/wiki/Bedtime_for_Bonzo"},
  {"title": "Believe you me", "text": "Believe me", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Believe you me"},
  {"title": "Bend someone's ear", "text": "Speak to someone at great length", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Bend someone's ear"},
  {"title": "Bent out of shape", "text": "Infuriated, annoyed. <em>She was all bent out of shape after hearing the president's speech.</em>", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Bent out of shape"},
  {"title": "Bickering", "text": "Fighting, arguing", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Bickering"},
  {"title": "Bless your pointy little head", "text": "A condescending phrase used to patronize someone for being foolish or not very bright. <em>You failed the exam because you thought the sun was a planet? Aw, bless your pointy little head.</em>", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Bless your pointy little head"},
  {"title": "Bonkers", "text": "Crazy", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Bonkers"},
  {"title": "Bouncing Off the Walls", "text": "Hyperactive", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Bouncing Off the Walls"},
  {"title": "Bumbershoot", "text": "Umbrella", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Bumbershoot"},
  {"title": "Busybox", "text": "An object someone likes to play or tinker with. <em>My son is playing with his new busybox, the piano</em>", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Busybox"},
  {"title": "Butter-side-up", "text": "Awaiting definition", "tags": "jQuery HTML5 CSS", "url": "https://docs.google.com/forms/d/e/1FAIpQLSdfmzsR2Z4hB9AG-CfEiPwZClB78tSY3SPVOWi4XbDCeGZQog/viewform"},
  {"title": "By any stretch of the imagination", "text": "Awaiting definition", "tags": "jQuery HTML5 CSS", "url": "https://docs.google.com/forms/d/e/1FAIpQLSdfmzsR2Z4hB9AG-CfEiPwZClB78tSY3SPVOWi4XbDCeGZQog/viewform"},
  {"title": "By George", "text": "An exclamation used to express astonishment, approval, etc.", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/By George"},
  {"title": "By Jove", "text": "Exclamation", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/By Jove"},
  {"title": "Can't beat it with a stick!", "text": "Awaiting definition", "tags": "jQuery HTML5 CSS", "url": "https://docs.google.com/forms/d/e/1FAIpQLSdfmzsR2Z4hB9AG-CfEiPwZClB78tSY3SPVOWi4XbDCeGZQog/viewform"},
  {"title": "Capice", "text": "Mother's favorite Sicilian mafia reference, meaning 'Do you understand?'", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Capice"},
  {"title": "Cat, stop tenderizing me!", "text": "Stop poking me", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Cat, stop tenderizing me!"},
  {"title": "Chew someone out", "text": "To criticize", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Chew someone out"},
  {"title": "Chowhound", "text": "Big eater. <em>She's being a real chow hound--I think she might be in a growth spurt! </em>", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Chowhound"},
  {"title": "Chup chup! (to the cat, pronounced \"choop\")", "text": "An encouragement to move or hurry", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Chup chup! (to the cat, pronounced \"choop\")"},
  {"title": "Clobber", "text": "To strike heavily", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Clobber"},
  {"title": "Come hell or high water", "text": "Whatever it takes", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Come hell or high water"},
  {"title": "Coming down with something", "text": "Contracting an illness. <em>I think you're coming down with something / I think you might be coming down with a cold</em>", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Coming down with something"},
  {"title": "Conked out", "text": "Asleep, zonked. <em>He sure is conked out! </em>", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Conked out"},
  {"title": "Cool it", "text": "Stop that", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Cool it"},
  {"title": "Cross (with someone)", "text": "Angry and annoyed, snappish. <em>She was quite cross and corrected me: 'it's woo-wee-sa!'</em>", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Cross (with someone)"},
  {"title": "Crotchety", "text": "Grumpy or irritable", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Crotchety"},
  {"title": "Daft", "text": "Definition unknown, despite multiple dictionary consultations. <em>Your friend is quite daft.</em>", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Daft"},
  {"title": "Death warmed over", "text": "Morbid or in extreme ill-health. <em>He came in looking like death warmed over; I think he's coming down with something.</em>", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Death warmed over"},
  {"title": "Dim recollection", "text": "A vague or distant memory. <em>I had a dim recollection that you’d taken off with that meemer.</em>", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Dim recollection"},
  {"title": "Ding-a-ling", "text": "Fool", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Ding-a-ling"},
  {"title": "Dingbat", "text": "Idiot", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Dingbat"},
  {"title": "Dinky", "text": "Little", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Dinky"},
  {"title": "Disaster waiting to happen", "text": "A risky plan or situation", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Disaster waiting to happen"},
  {"title": "Doll", "text": "A dear or a hottie. <em>Jordan's a doll</em>", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Doll"},
  {"title": "Don't go away mad, just go away.", "text": "Imperative: leave", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Don't go away mad, just go away."},
  {"title": "Doozie", "text": "Something large or excellent. <em>Doozie is a doozie, I'd say.</em>", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Doozie"},
  {"title": "Down the hatch", "text": "Swallowed. <em>Ok, down the hatch with this pill! </em>", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Down the hatch"},
  {"title": "Down-side-up", "text": "Upside down", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Down-side-up"},
  {"title": "Downright nippy", "text": "Irritable, hostile, or aggressive", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Downright nippy"},
  {"title": "Dubious (people)", "text": "Awaiting definition", "tags": "jQuery HTML5 CSS", "url": "https://docs.google.com/forms/d/e/1FAIpQLSdfmzsR2Z4hB9AG-CfEiPwZClB78tSY3SPVOWi4XbDCeGZQog/viewform"},
  {"title": "Ducks in a row", "text": "In order, prepared", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Ducks in a row"},
  {"title": "Dune buggy", "text": "Awaiting definition", "tags": "jQuery HTML5 CSS", "url": "https://docs.google.com/forms/d/e/1FAIpQLSdfmzsR2Z4hB9AG-CfEiPwZClB78tSY3SPVOWi4XbDCeGZQog/viewform"},
  {"title": "Eat my hat", "text": "Be quite upset. <em>If George the Younger gets elected, I'll eat my hat.</em> <strong>Mommentary: My dad used to say that.</strong>", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Eat my hat"},
  {"title": "Egad", "text": "Awaiting definition", "tags": "jQuery HTML5 CSS", "url": "https://docs.google.com/forms/d/e/1FAIpQLSdfmzsR2Z4hB9AG-CfEiPwZClB78tSY3SPVOWi4XbDCeGZQog/viewform"},
  {"title": "Egg-shaped", "text": "Awaiting definition", "tags": "jQuery HTML5 CSS", "url": "https://docs.google.com/forms/d/e/1FAIpQLSdfmzsR2Z4hB9AG-CfEiPwZClB78tSY3SPVOWi4XbDCeGZQog/viewform"},
  {"title": "Fewidgewator", "text": "Refridgerator <strong>Mommentary: Among mom’s favorite kidisms</strong>", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Fewidgewator"},
  {"title": "Figment of my imagination", "text": "Imaginary", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Figment of my imagination"},
  {"title": "Finicky", "text": "Synonym: picky, overly selective", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Finicky"},
  {"title": "For the birds!", "text": "Not good. <em>This oatmeal is for the birds.</em> <strong>Mommentary: A momism from a surprising source: dad</strong>", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/For the birds!"},
  {"title": "Full of beans", "text": "Silly", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Full of beans"},
  {"title": "Gadzooks", "text": "Awaiting definition", "tags": "jQuery HTML5 CSS", "url": "https://docs.google.com/forms/d/e/1FAIpQLSdfmzsR2Z4hB9AG-CfEiPwZClB78tSY3SPVOWi4XbDCeGZQog/viewform"},
  {"title": "Geegaw", "text": "Awaiting definition", "tags": "jQuery HTML5 CSS", "url": "https://docs.google.com/forms/d/e/1FAIpQLSdfmzsR2Z4hB9AG-CfEiPwZClB78tSY3SPVOWi4XbDCeGZQog/viewform"},
  {"title": "George the Lesser", "text": "George W. Bush", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/George the Lesser"},
  {"title": "George the Younger", "text": "Refers to George W. Bush", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/George the Younger"},
  {"title": "Get boosted or launched (e.g. in the morning)", "text": "Get up", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Get boosted or launched (e.g. in the morning)"},
  {"title": "Give it the old college try", "text": "To attempt something difficult", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Give it the old college try"},
  {"title": "Going at a good clip", "text": "Moving quickly", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Going at a good clip"},
  {"title": "Go over like a lead balloon", "text": "Something did not go over well at all, not be well received, be unpopular, even resented. <em>When I offered to share some of my hot sauce, it went over like a lead balloon.</em>", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Go over like a lead balloon"},
  {"title": "Good enough for government work", "text": "Awaiting definition", "tags": "jQuery HTML5 CSS", "url": "https://docs.google.com/forms/d/e/1FAIpQLSdfmzsR2Z4hB9AG-CfEiPwZClB78tSY3SPVOWi4XbDCeGZQog/viewform"},
  {"title": "Goodness Gracious", "text": "Exclamation: surprise", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Goodness Gracious"},
  {"title": "Grass", "text": "Marijuana <strong>Mommentary: I think that's a common euphemism among people in my age group, but I might be unusual in still using the word while others have moved on.</strong>", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Grass"},
  {"title": "Great zot", "text": "Exclamation", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Great zot"},
  {"title": "Grungy", "text": "Dirty, grimey", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Grungy"},
  {"title": "Hair raising experience", "text": "A scary experience", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Hair raising experience"},
  {"title": "Hare brained (scheme)", "text": "Foolish scheme", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Hare brained (scheme)"},
  {"title": "Head of steam", "text": "Awaiting definition", "tags": "jQuery HTML5 CSS", "url": "https://docs.google.com/forms/d/e/1FAIpQLSdfmzsR2Z4hB9AG-CfEiPwZClB78tSY3SPVOWi4XbDCeGZQog/viewform"},
  {"title": "Health adventure", "text": "An annoying and/or scary health saga.", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Health adventure"},
  {"title": "Heavenly days", "text": "Exclamation", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Heavenly days"},
  {"title": "Heavens to Betsy", "text": "Exclamation", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Heavens to Betsy"},
  {"title": "Hell in a hand-basket", "text": "Awaiting definition", "tags": "jQuery HTML5 CSS", "url": "https://docs.google.com/forms/d/e/1FAIpQLSdfmzsR2Z4hB9AG-CfEiPwZClB78tSY3SPVOWi4XbDCeGZQog/viewform"},
  {"title": "To high-tail it", "text": "To flee or leave quickly", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/To high-tail it"},
  {"title": "Hold your horses", "text": "Imperative: calm down or be patient", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Hold your horses"},
  {"title": "Honorable horrors", "text": "Exclamation", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Honorable horrors"},
  {"title": "Hooie ballooie", "text": "Nonsense or bullshit", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Hooie ballooie"},
  {"title": "Hoot, as in \"What a hoot!\" and \"I don't give a hoot!\"", "text": "1.) Hilarious. 2) Don't care at all.", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Hoot, as in \"What a hoot!\" and \"I don't give a hoot!\""},
  {"title": "Hot Diggity!", "text": "Exclamation", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Hot Diggity!"},
  {"title": "Huh-what", "text": "Mother's odd aspirated h on question words that only began when she 'discovered she does it' in linguistics grad school.. <em>But son, huh-why is huh-what a momism? Huh-where did you get that idea and huh-when? Huh-who's idea is this?</em>", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Huh-what"},
  {"title": "Hunkey Dorey", "text": "All is well", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Hunkey Dorey"},
  {"title": "I have a yen for", "text": "Hankering", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/I have a yen for"},
  {"title": "I wish this dang thing would stop taking pictures of my pocket. (*click* I wish it would quit taking pictures of the inside of my pocket, to be exact.)", "text": "Mom's technological frustration at the camera in her pocket", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/I wish this dang thing would stop taking pictures of my pocket. (*click* I wish it would quit taking pictures of the inside of my pocket, to be exact.)"},
  {"title": "I'm gonna go \"turn into a pumpkin\"", "text": "Go to sleep", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/I'm gonna go \"turn into a pumpkin\""},
  {"title": "I'm gonna hang up my shingle (ex. and become a babysitter)", "text": "Awaiting definition", "tags": "jQuery HTML5 CSS", "url": "https://docs.google.com/forms/d/e/1FAIpQLSdfmzsR2Z4hB9AG-CfEiPwZClB78tSY3SPVOWi4XbDCeGZQog/viewform"},
  {"title": "I'm not getting any younger", "text": "I'm getting older", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/I'm not getting any younger"},
  {"title": "If you ... , your name is \"dog\"", "text": "Your name is mud (cat version)", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/If you ... , your name is \"dog\""},
  {"title": "If you ask me", "text": "In my opinion. <em>Your friend seems a little dubious, if you ask me.</em>", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/If you ask me"},
  {"title": "In cahoots (with)", "text": "Awaiting definition", "tags": "jQuery HTML5 CSS", "url": "https://docs.google.com/forms/d/e/1FAIpQLSdfmzsR2Z4hB9AG-CfEiPwZClB78tSY3SPVOWi4XbDCeGZQog/viewform"},
  {"title": "In my view", "text": "In my opinion. <em>Your friend seems a little daft, in my view</em>", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/In my view"},
  {"title": "In your hot little hands", "text": "In your hands. <em>What channel shall I change to, now that I have the remote in my hot little hands?</em>", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/In your hot little hands"},
  {"title": "Is dragging his/her anchor", "text": "Moving slowly", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Is dragging his/her anchor"},
  {"title": "Is that goat cheese? Ewe!", "text": "Eye-rolling pun <strong>Mommentary: Mom dislikes goat cheese</strong>", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Is that goat cheese? Ewe!"},
  {"title": "It takes 10-attaboys to make up for 1-aw-shit", "text": "It's easier to prevent mistakes than to clean them up <strong>Mommentary: Honorary grand-momism</strong>", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/It takes 10-attaboys to make up for 1-aw-shit"},
  {"title": "It's been known to happen", "text": "Awaiting definition", "tags": "jQuery HTML5 CSS", "url": "https://docs.google.com/forms/d/e/1FAIpQLSdfmzsR2Z4hB9AG-CfEiPwZClB78tSY3SPVOWi4XbDCeGZQog/viewform"},
  {"title": "Jimminy Cricket!", "text": "A mild exclamation of surprise, emotion, or awe.", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Jimminy Cricket!"},
  {"title": "Ka-broken", "text": "Broken. <em>My tea-kettle is ka-broken</em>", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Ka-broken"},
  {"title": "Keel over", "text": "Fall as in fainting", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Keel over"},
  {"title": "Keep your eyes peeled", "text": "Be on the lookout", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Keep your eyes peeled"},
  {"title": "Keep your shirt on", "text": "Imperative: calm down or be patient", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Keep your shirt on"},
  {"title": "Kerfuffle", "text": "A conflict", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Kerfuffle"},
  {"title": "Kiddely (and kididely)", "text": "Kids", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Kiddely (and kididely)"},
  {"title": "Killer baby", "text": "Usually refers to her daughter", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Killer baby"},
  {"title": "Knickers in a knot", "text": "Upset", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Knickers in a knot"},
  {"title": "Let's get this show on the road", "text": "Let's go. <em>Don't get cross with me! </em>", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Let's get this show on the road"},
  {"title": "Lickety-split", "text": "Right away", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Lickety-split"},
  {"title": "Like a dose of salts", "text": "To consume something quickly. <em>Mom: We'd better buy kefir. You go through it like a dose of salts. *pause* Mom: You'd better go put that on the list.</em>", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Like a dose of salts"},
  {"title": "Like a gemstone in a rock tumbler", "text": "Shaken but not stirred. <em>On that flight, I was like a gemstone in a rock tumbler</em> <strong>Mommentary: Mom just made it up but it was good. N.B. mom gets motion sickness easily</strong>", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Like a gemstone in a rock tumbler"},
  {"title": "Like gangbusters", "text": "With great speed, intensity, vigour, impact, or success.. <em>Don't worry, at restaurants, I tip like gangbusters.</em>", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Like gangbusters"},
  {"title": "Lord love a duck", "text": "Exclamation", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Lord love a duck"},
  {"title": "Lovey", "text": "Refers to her daughter", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Lovey"},
  {"title": "Madder than a wet hen", "text": "I assume this means one is quite angry", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Madder than a wet hen"},
  {"title": "Made quick work of (e.g. that sandwich!)", "text": "To consume or use up quickly", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Made quick work of (e.g. that sandwich!)"},
  {"title": "Major-league pain in the butt", "text": "A major pain. <em>A certain Quaker is a mixed blessing, sometimes pleasant and sometimes a major-league pain in the butt. </em> <strong>Mommentary: I guess other people don’t say that, come to think of it. I think I got that from my mom. </strong>", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Major-league pain in the butt"},
  {"title": "Make yourself scarce.", "text": "Imperative: leave", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Make yourself scarce."},
  {"title": "Making a ruckus", "text": "Making a lot of noise", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Making a ruckus"},
  {"title": "Meemer", "text": "Vacuum cleaner (baby talk)", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Meemer"},
  {"title": "Mid-section", "text": "Waist", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Mid-section"},
  {"title": "More power to you, (son!)", "text": "The usual definition is that one approves of what someone is doing and hopes it will be successful. However, in mom's case, there is also a skepticism that the scheme will be successful.", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/More power to you, (son!)"},
  {"title": "My brain went whiffle", "text": "Synonym: I had a senior moment", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/My brain went whiffle"},
  {"title": "Neck of the woods", "text": "Area, neighbourhood", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Neck of the woods"},
  {"title": "Nick of time", "text": "Just in time", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Nick of time"},
  {"title": "No Muss, No Fuss", "text": "Simple, easy", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/No Muss, No Fuss"},
  {"title": "No spring chicken.", "text": "Old", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/No spring chicken."},
  {"title": "Noggin", "text": "Head", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Noggin"},
  {"title": "Not in Great Shape", "text": "Not feeling well, not in good condition", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Not in Great Shape"},
  {"title": "Not to be too much of a linguist", "text": "Mother is definitely too much of a linguist. <em>Not to be too much of a linguist but what a diphtong! </em>", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Not to be too much of a linguist"},
  {"title": "Nothing left of someone but a grease spot.", "text": "Awaiting definition", "tags": "jQuery HTML5 CSS", "url": "https://docs.google.com/forms/d/e/1FAIpQLSdfmzsR2Z4hB9AG-CfEiPwZClB78tSY3SPVOWi4XbDCeGZQog/viewform"},
  {"title": "Oldie but a goodie", "text": "A classic", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Oldie but a goodie"},
  {"title": "On a jag", "text": "Awaiting definition", "tags": "jQuery HTML5 CSS", "url": "https://docs.google.com/forms/d/e/1FAIpQLSdfmzsR2Z4hB9AG-CfEiPwZClB78tSY3SPVOWi4XbDCeGZQog/viewform"},
  {"title": "On the horn", "text": "On the phone", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/On the horn"},
  {"title": "Ornery", "text": "Grumpy or irritable", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Ornery"},
  {"title": "Out of Commission", "text": "Awaiting definition", "tags": "jQuery HTML5 CSS", "url": "https://docs.google.com/forms/d/e/1FAIpQLSdfmzsR2Z4hB9AG-CfEiPwZClB78tSY3SPVOWi4XbDCeGZQog/viewform"},
  {"title": "Out of this world", "text": "Excellent", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Out of this world"},
  {"title": "Oy vey", "text": "Mom's Yiddish streak: expresses annoyance", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Oy vey"},
  {"title": "Pain in the neck", "text": "Irritating", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Pain in the neck"},
  {"title": "Perfunctory", "text": "Awaiting definition", "tags": "jQuery HTML5 CSS", "url": "https://docs.google.com/forms/d/e/1FAIpQLSdfmzsR2Z4hB9AG-CfEiPwZClB78tSY3SPVOWi4XbDCeGZQog/viewform"},
  {"title": "Persnickety", "text": "Picky", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Persnickety"},
  {"title": "Piece of work", "text": "Adjective meaning someone is unusually unpleasant, difficult, or behaves particularly badly.. <em>You're a piece of work, lovey.</em>", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Piece of work"},
  {"title": "Pipe down", "text": "Quiet down", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Pipe down"},
  {"title": "Pitching a fit", "text": "Become extremely upset or angry in a loud and uncontrolled way, having a tantrum, making a scene", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Pitching a fit"},
  {"title": "Poke around", "text": "Synonym: to look around. <em>I'm going to go poke around the Chalet.</em>", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Poke around"},
  {"title": "Pole-axed", "text": "Exhausted", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Pole-axed"},
  {"title": "Polish it off", "text": "Eat all of a dish", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Polish it off"},
  {"title": "Put a lid on it!", "text": "Exclamation: to be quiet, shut up", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Put a lid on it!"},
  {"title": "Put that into your equation", "text": "Consider that <strong>Mommentary: (Lowell-ism)</strong>", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Put that into your equation"},
  {"title": "Put the Kibosh On", "text": "To cancel", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Put the Kibosh On"},
  {"title": "Put/grow hair on your chest", "text": "Awaiting definition", "tags": "jQuery HTML5 CSS", "url": "https://docs.google.com/forms/d/e/1FAIpQLSdfmzsR2Z4hB9AG-CfEiPwZClB78tSY3SPVOWi4XbDCeGZQog/viewform"},
  {"title": "Rattling around", "text": "Awake and moving around the house. <em>I could hear him rattling around long after I turned into a pumpkin.</em>", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Rattling around"},
  {"title": "Recipe for disaster", "text": "Something that is likely to result in disaster", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Recipe for disaster"},
  {"title": "Roaring Around", "text": "Awaiting definition", "tags": "jQuery HTML5 CSS", "url": "https://docs.google.com/forms/d/e/1FAIpQLSdfmzsR2Z4hB9AG-CfEiPwZClB78tSY3SPVOWi4XbDCeGZQog/viewform"},
  {"title": "Roll up your pants, it's too late to save your shoes", "text": "Awaiting definition", "tags": "jQuery HTML5 CSS", "url": "https://docs.google.com/forms/d/e/1FAIpQLSdfmzsR2Z4hB9AG-CfEiPwZClB78tSY3SPVOWi4XbDCeGZQog/viewform"},
  {"title": "Roost", "text": "To sit, rest. <em>I'm looking for a bench upon which to roost.</em> <strong>Mommentary: Seems to me a perch is more temporary.</strong>", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Roost"},
  {"title": "Rotten in Denmark", "text": "Awaiting definition", "tags": "jQuery HTML5 CSS", "url": "https://docs.google.com/forms/d/e/1FAIpQLSdfmzsR2Z4hB9AG-CfEiPwZClB78tSY3SPVOWi4XbDCeGZQog/viewform"},
  {"title": "Ruffled his feathers", "text": "To have irritated or offended someone", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Ruffled his feathers"},
  {"title": "Sanford Sharpie", "text": "A permanent marker", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Sanford Sharpie"},
  {"title": "Scarcer than hen's teeth", "text": "Extremely rare, nonexistent", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Scarcer than hen's teeth"},
  {"title": "Schlep", "text": "Mom's Yiddish streak: it means to carry something heavy or bulky", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Schlep"},
  {"title": "Schtick", "text": "Mom's Yiddish streak: a show or an act", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Schtick"},
  {"title": "Scream bloody murder", "text": "Scream loudly", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Scream bloody murder"},
  {"title": "Sell fwoop = swell foop", "text": "A fell swoop", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Sell fwoop = swell foop"},
  {"title": "Someone could talk the leaves off a tree", "text": "Someone often speaks at great length <strong>Mommentary: That comes from Debbie Hotch, college roommate</strong>", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Someone could talk the leaves off a tree"},
  {"title": "Skedaddle", "text": "Leave rapidly", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Skedaddle"},
  {"title": "Smack dab in the middle", "text": "Exactly in the middle", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Smack dab in the middle"},
  {"title": "Smart cookie", "text": "Noun, an intelligent person", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Smart cookie"},
  {"title": "Snatching defeat from the jaws of victory ", "text": "A play on the inverse phrase (snatching victory from the jaws of defeat), this momism means losing something that was nearly won. <strong>Mommentary: That phrase was popular with respect to Duke basketball in the days before the present - successful - coach Mike Krzyzewski</strong>", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Snatching defeat from the jaws of victory "},
  {"title": "Snippy.", "text": "Awaiting definition", "tags": "jQuery HTML5 CSS", "url": "https://docs.google.com/forms/d/e/1FAIpQLSdfmzsR2Z4hB9AG-CfEiPwZClB78tSY3SPVOWi4XbDCeGZQog/viewform"},
  {"title": "Snorkel", "text": "To nuzzle. <em>Cat, quit snorkeling me! </em>", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Snorkel"},
  {"title": "Snuffocate", "text": "Suffocate. <em>Get me out of here before I snuffocate! </em>", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Snuffocate"},
  {"title": "Soccer slides", "text": "Slip-on sandals", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Soccer slides"},
  {"title": "Sonnn", "text": "Son, with extended n sound. <em>Sonnnn, why did you wake me from my nap?</em>", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Sonnn"},
  {"title": "Speak of the devil", "text": "The person mom just mentioned has appeared", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Speak of the devil"},
  {"title": "Splinker", "text": "Splinter, baby talk from the middle child", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Splinker"},
  {"title": "Squabbling", "text": "To bicker, argue", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Squabbling"},
  {"title": "Stinker", "text": "A contemptible or very unpleasant person or thing.. <em>That little stinker took off with my socks! </em>", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Stinker"},
  {"title": "Stranger things have happened", "text": "Awaiting definition", "tags": "jQuery HTML5 CSS", "url": "https://docs.google.com/forms/d/e/1FAIpQLSdfmzsR2Z4hB9AG-CfEiPwZClB78tSY3SPVOWi4XbDCeGZQog/viewform"},
  {"title": "String beans", "text": "Awaiting definition", "tags": "jQuery HTML5 CSS", "url": "https://docs.google.com/forms/d/e/1FAIpQLSdfmzsR2Z4hB9AG-CfEiPwZClB78tSY3SPVOWi4XbDCeGZQog/viewform"},
  {"title": "Suffice It To Say", "text": "It is enough to say this and no more, as in Suffice it to say that the judge was furious when the invitation was withdrawn.", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Suffice It To Say"},
  {"title": "Sure As God Made Little Green Apples", "text": "Certain", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Sure As God Made Little Green Apples"},
  {"title": "Sweet tooth", "text": "Love of sugar", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Sweet tooth"},
  {"title": "Take a long walk off a short dock", "text": "Imperative: leave <strong>Mommentary: (mom's mom)</strong>", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Take a long walk off a short dock"},
  {"title": "Take off with", "text": "To take", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Take off with"},
  {"title": "Taken with", "text": "To like. <em>My daughter was quite taken with 'woo-wee-sa.' </em>", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Taken with"},
  {"title": "That's droll", "text": "Consulting the dictionary multiple times has not clarified this meaning", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/That's droll"},
  {"title": "The linguini listserv", "text": "Mother's linguistic's department listserv", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/The linguini listserv"},
  {"title": "The photo hobby", "text": "Mother's love of photography", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/The photo hobby"},
  {"title": "The US mule", "text": "The US Mail", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/The US mule"},
  {"title": "The whole shebangdasium", "text": "Awaiting definition", "tags": "jQuery HTML5 CSS", "url": "https://docs.google.com/forms/d/e/1FAIpQLSdfmzsR2Z4hB9AG-CfEiPwZClB78tSY3SPVOWi4XbDCeGZQog/viewform"},
  {"title": "Thee and me", "text": "Awaiting definition", "tags": "jQuery HTML5 CSS", "url": "https://docs.google.com/forms/d/e/1FAIpQLSdfmzsR2Z4hB9AG-CfEiPwZClB78tSY3SPVOWi4XbDCeGZQog/viewform"},
  {"title": "These parts", "text": "This area or neighbourhood", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/These parts"},
  {"title": "They would get along like a house afire", "text": "They would get along well", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/They would get along like a house afire"},
  {"title": "Three eggs in a basket is finer 'en fourteen in the chicken coop!", "text": "A fake momism used to tease mother's strange sayings <strong>Mommentary: Apocryphal</strong>", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Three eggs in a basket is finer 'en fourteen in the chicken coop!"},
  {"title": "Tickled Pink", "text": "Very amused", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Tickled Pink"},
  {"title": "Tougher than boiled owl", "text": "Very hard to chew", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Tougher than boiled owl"},
  {"title": "Trouper", "text": "A loyal, dependable worker or participant in an undertaking", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Trouper"},
  {"title": "Turkey (i.e. road rage)", "text": "An inept person", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Turkey (i.e. road rage)"},
  {"title": "Umpteenth time (Umpteen Times)", "text": "Awaiting definition", "tags": "jQuery HTML5 CSS", "url": "https://docs.google.com/forms/d/e/1FAIpQLSdfmzsR2Z4hB9AG-CfEiPwZClB78tSY3SPVOWi4XbDCeGZQog/viewform"},
  {"title": "Up the wazoo", "text": "A lot of something. <em>We have tea up the wazoo! </em>", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Up the wazoo"},
  {"title": "Went belly-up", "text": "Died. <em>After they turned down the heat, all my orchids went belly up.</em>", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Went belly-up"},
  {"title": "Went the Way of the Dodo", "text": "Went extinct or obsolete", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Went the Way of the Dodo"},
  {"title": "Were you raised in a barn? Kidism: Yes!", "text": "Awaiting definition", "tags": "jQuery HTML5 CSS", "url": "https://docs.google.com/forms/d/e/1FAIpQLSdfmzsR2Z4hB9AG-CfEiPwZClB78tSY3SPVOWi4XbDCeGZQog/viewform"},
  {"title": "What have you gotten into", "text": "What have you opened or taken from?. <em>Who got into the cookies?</em>", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/What have you gotten into"},
  {"title": "What-all", "text": "Plural of what. <em>I have no clue as to what-all you-all saw.</em>", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/What-all"},
  {"title": "Whifflebrain", "text": "Airhead", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Whifflebrain"},
  {"title": "White knuckle trip", "text": "A terrifying journey", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/White knuckle trip"},
  {"title": "Who-all", "text": "Plural of who. <em>Who-all did you go to France with?</em> <strong>Mommentary: Referring to the likelihood that the answer to the question has several parts.</strong>", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Who-all"},
  {"title": "Whole kit and kaboodle", "text": "Awaiting definition", "tags": "jQuery HTML5 CSS", "url": "https://docs.google.com/forms/d/e/1FAIpQLSdfmzsR2Z4hB9AG-CfEiPwZClB78tSY3SPVOWi4XbDCeGZQog/viewform"},
  {"title": "Whole shooting match", "text": "Awaiting definition <strong>Mommentary: Because I caught myself saying it the other day, then mom said it today :)</strong>", "tags": "jQuery HTML5 CSS", "url": "https://docs.google.com/forms/d/e/1FAIpQLSdfmzsR2Z4hB9AG-CfEiPwZClB78tSY3SPVOWi4XbDCeGZQog/viewform"},
  {"title": "Winks", "text": "A brief nap.. <em>I'm going to grab a quick wink.</em>", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Winks"},
  {"title": "Within an inch of his/her/their life/lives", "text": "Awaiting definition", "tags": "jQuery HTML5 CSS", "url": "https://docs.google.com/forms/d/e/1FAIpQLSdfmzsR2Z4hB9AG-CfEiPwZClB78tSY3SPVOWi4XbDCeGZQog/viewform"},
  {"title": "Wooze", "text": "Kidism for 'lose'. <em>Don’t wooze it.</em>", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Wooze"},
  {"title": "Woo-wee-sa", "text": "Kidism for Louisa <strong>Mommentary: My daughter used to be very taken with our neighbor Louisa except she pronounced it Eww-eesa. Mom started imitating her, saying 'eww-wee-sa' but she crossly corrected mother to 'woo-wee-sa'. This same daughter also used to spell Emily’s name 'MOE'</strong>", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Woo-wee-sa"},
  {"title": "Worrywart", "text": "Someone with a tendency to worry habitually, often needlessly.", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Worrywart"},
  {"title": "Ye gods and little catfish, or ye gods and little fishes", "text": "Awaiting definition", "tags": "jQuery HTML5 CSS", "url": "https://docs.google.com/forms/d/e/1FAIpQLSdfmzsR2Z4hB9AG-CfEiPwZClB78tSY3SPVOWi4XbDCeGZQog/viewform"},
  {"title": "Yea high [accompanied by pointing]", "text": "Indicates that something is as high as mom is pointing, usually not very high.. <em>That cat went past the wall about yea high with that paintbrush in her mouth.</em>", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Yea high [accompanied by pointing]"},
  {"title": "Yes, cat. no, cat. maybe, cat", "text": "Expression of sarcastic subordination to the cat", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Yes, cat. no, cat. maybe, cat"},
  {"title": "You have such a good [body part] for [task]. (ex. good eye for composition, Ear, idiosyncrasy)", "text": "Mother's preferred momism for describing an extraordinary skill", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/You have such a good [body part] for [task]. (ex. good eye for composition, Ear, idiosyncrasy)"},
  {"title": "Your name is mud", "text": "You're in trouble", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Your name is mud"},
  {"title": "Zonked", "text": "Tired. <em>That (sleeping) baby is zonked! </em>", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Zonked"},
  {"title": "Zories", "text": "Japanese-style flip-flops, often made of woven rice straw, sort of like tatamis you can wear on your feet. <strong>Mommentary: Zories were a fad back when I was young. I haven't seen them in years.</strong>", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Zories"},
  {"title": "Zowie", "text": "Exclamation", "tags": "jQuery HTML5 CSS", "url": "http://www.dictionary.com/browse/Zowie"},  
]};
